### ISSUE TITLE
The local reference need to be changed to package reference.

### ISSUE THREAD

**Issue by maooson** [VirtoCommerce/vc-platform-core#1]
Hi tatarincev,

Why not use the package reference? (Install from nuget)

https://github.com/VirtoCommerce/vc-platform-core/blob/c47b1b7f1eafe051d6990c153681b77d865fc35c/VirtoCommerce.Platform.Core/VirtoCommerce.Platform.Core.csproj#L16

**Comment by tatarincev** [comment]
Probably VS added this reference by pressing Shift+Alt+F11, I'll check and replace to nuget dependency.
Thank you for your attention! :)

**Comment by maooson** [comment]
I have created a PR #2 yet.

**Comment by tatarincev** [comment]
@maooson  Could you confirm CLA agreement, please?

**Comment by maooson** [comment]
@tatarincev It's fine now

**Comment by tatarincev** [comment]
Yes, fine. Welcome to VirtoCommerce contributors family :)

**Comment by maooson** [comment]
It's my pleasure, you did a good job.
