### ISSUE TITLE
Migrate changes made in the platform 2.x to the platform 3.x

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-platform-core#103]
The VirtoCommerce Platform v3.x is developed parallel to the VC Platform 2.x. Last code sync have been executed between 05/30/2018 (386d5df) and 06/04/2018 (85cbee5), and all changes made to the VC Platform 2.x since that time are not present in the VC Platform 3.x.

In this task, we need to actualize the VC Platform 3.x codebase. To do that, we'll need to migrate all changes made to the VC Platform 2.x and all ported modules since 386d5df.

**Comment by tatarincev** [comment]
Need to implement  Azure AD authentication by using the OpenIddict library.
