### ISSUE TITLE
Detect all DB schema differences between 2.x and 3.0 platform and modules versions

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#127]
The primary goal is to transfer all existing data from the version 2.x database to the new database scheme that actual for platform 3.0 by manually running the script.

Probably we can use DB schema comparison tools built-in VS to get differences.
** Known DB schema changes: **
- Security tables now is completely different in 3.0 we use default ASP.NET Identity tables
- No more TPT inheritance in EF so all classes hierarchy now is mapped   into one table and is difference by discriminator column (Member table, Order, Cart)

**Comment by kostyrin** [comment]
https://virto365-my.sharepoint.com/:x:/g/personal/ako_virtoway_com/Ef1BjU8mJyZBromPUe1Xg_wBVBw4J9A8v6Bcq_mMylBfGg?e=ctw5TN
