### ISSUE TITLE
what's the password of the default account 'admin'

### ISSUE THREAD

**Issue by 68681395** [VirtoCommerce/vc-platform-core#18]
As title said, I can't find the pwd of the account admin, can you help me? many thanks.

**Comment by asvishnyakov** [comment]
@68681395 Hello! As said in [our docs](https://virtocommerce.com/docs/vc2devguide/deployment/platform-deployment/deploy-from-source-code) and [on demo site](https://admin-demo.virtocommerce.com/#/login) the password of the default account 'admin' is '**store**'

**Comment by 68681395** [comment]
@asvishnyakov Big thank for your quick response.
