### ISSUE TITLE
Find out and document all platform API breaking changes and eliminate differences

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#197]
For this task need to compare resulting API of 2.x and 3.0 platform version and all modules and write down the differences to this issue.

**Comment by anivirtoway** [comment]
Here is a good idea of ​​the changes in api
[diff.zip](https://github.com/VirtoCommerce/vc-platform-core/files/3041969/diff.zip)

**Comment by anivirtoway** [comment]
All needed files to generate report is here. Require Java. Just run diff_java.bat
[swagger-diff.zip](https://github.com/VirtoCommerce/vc-platform-core/files/3042266/swagger-diff.zip)
