### ISSUE TITLE
Test of modules management functionality

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#198]
- Modules manual installation from zip package
- Modules installation from update server (json file)
- Errors handling and display  during initialization
- Modules dependency resolving during installation from update server

[Modularity test scenarios.pdf](https://github.com/VirtoCommerce/vc-platform-core/files/3030243/Modularity.test.scenarios.pdf)

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56279375-42ceea00-6108-11e9-9bc6-36e9f15c0106.png)

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56291305-59d00500-6125-11e9-8e4e-195ad80da9ae.png)

A module declared a dependency on another module which is not declared to be loaded. Missing module(s): VirtoCommerce.Inventory, VirtoCommerce.Store

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56292861-45d9d280-6128-11e9-8d25-c1d6d6426895.png)

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56354823-074e2180-61d5-11e9-8436-81140c2d7ed4.png)
major and minor versions

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56355016-87748700-61d5-11e9-8fb6-c51cf8146793.png)
install module with dependencies if has correct versions

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56355712-4d0be980-61d7-11e9-9314-380f53cd33d6.png)
installed catalog even those dependency has v. 3.1.0

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56356420-251d8580-61d9-11e9-8043-3a0038f40ad5.png)
![image](https://user-images.githubusercontent.com/8361000/56356446-336ba180-61d9-11e9-9868-1ac844edefd2.png)
exmpl 5 : don't install store v.3.0 when catalog 2.5 with dep. core 2.0 and search 2.0

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56378432-587a0780-620d-11e9-8c6b-890c4d2f1ae2.png)
![image](https://user-images.githubusercontent.com/8361000/56378481-72b3e580-620d-11e9-883b-acb07494f48e.png)

exmpl 6: don't install Store 2.5(dep core 2.5) when core 3.0, catalog 2.0(dep. core 3.0)

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56378756-43ea3f00-620e-11e9-90ea-dcea20f6279b.png)
exmpl 7:  don't install store 2.5(dep core 2.5), catalog 2.0(dep. core 3.0), inventory 2.0(dep. core 2.0)

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56379036-0cc85d80-620f-11e9-81f3-22b8b69865b2.png)
exmpl 8

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/56412031-2a370f00-6283-11e9-95e0-83a496c9e068.png)
uninstall ex.1

**Comment by kostyrin** [comment]
#211 fix also
