### ISSUE TITLE
CI/CD: Prepare and upload sample data for 3.0 version

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#221]
Need to create the new pack with sample data based on exists for 2.0 and upload into public location  http://virtocommerce.blob.core.windows.net/sample-data  in order to be able discovered for new platform installations. 
Need to check that resulting Json doesn't contains full type names e.g  "$type" and '$values'

**Comment by kostyrin** [comment]
https://virto365-my.sharepoint.com/:u:/g/personal/ako_virtoway_com/EfgOXxg_j4RHgeyhz7zWIAQBkMXgYNY0jI_apmDVKs7U2Q?e=UpoaCF
