### ISSUE TITLE
CI/CD: Adopt powershell script based on VirtoCommerce.Module  nuget package to build modules with 3.x version

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#229]
Link to 2.x version https://github.com/VirtoCommerce/vc-platform/tree/master/VirtoCommerce.Module
Need to change exists script to be able build modules with 3.x versions.

**Comment by artem-dudarev** [comment]
Also need to add support for VS 2019:
https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Module/tools/VirtoCommerce.Module.psm1#L23

**Comment by arsen74** [comment]
Implemented here - https://github.com/VirtoCommerce/vc-platform-core/pull/237/commits/fbd1ee9eac0b57af1bc80912b1379f7d7f310eae
