### ISSUE TITLE
Add possibility to restart platform from UI

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#232]

**Comment by arsen74** [comment]
Can't be implemented with current .net core 2.2.
But after release .net core 3.0 - can
In .net core 3.0 AssemblyLoadContext will be collectible which means can be unloaded - https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Runtime/Loader/AssemblyLoadContext.cs
More information is here - https://www.strathweb.com/2019/01/collectible-assemblies-in-net-core-3-0/

**Comment by tatarincev** [comment]
can we make a command file (.bat) that will contains a some commands for restart dotnet.exe process and run it from application?

**Comment by arsen74** [comment]
Added restart platform ability via dotnet process restarting
