### ISSUE TITLE
angular.toLowerCase not found

### ISSUE THREAD

**Issue by anivirtoway** [VirtoCommerce/vc-platform-core#236]
1. clone master brunch
2. install all npm modules
3. build all webpack modules
4. build backend
5. start platform.web - see angular.toLowerCase not found - exception in browser console, and no admin panel started

**Comment by arsen74** [comment]
Fixes - just fix version of js libraries dependecies - via npm shrink

**Comment by arsen74** [comment]
Fixed here - https://github.com/VirtoCommerce/vc-platform-core/pull/237/commits/82ff9214542d93d9a7d4596a38ac4d5b075c2de0
