### ISSUE TITLE
error while creating dinamic content item

### ISSUE THREAD

**Issue by anivirtoway** [VirtoCommerce/vc-platform-core#275]
![2019-05-23_09-51-53.png](https://images.zenhubusercontent.com/5c40aaa981fb545d1bd592d5/d8c8b06c-0616-4550-9561-7c1c294071db)

![2019-05-23_09-54-10.png](https://images.zenhubusercontent.com/5c40aaa981fb545d1bd592d5/352f4ad3-7eca-45c6-93ea-6f27047b92d8)

![2019-05-23_09-49-55.png](https://images.zenhubusercontent.com/5c40aaa981fb545d1bd592d5/17acb505-2d52-497e-8a0b-54d644e89e78)

**Comment by anivirtoway** [comment]
can't reproduce, maybe already fixed

**Comment by kostyrin** [comment]
yeap, fixed same errors
