### ISSUE TITLE
Migrate the Swagger and Swashbuckle to the new versions

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#3]
- Migrate to new version of Swagger and Swashbuckle
https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio
- Migrate exist swashbuckle UI to the new version
previous version https://github.com/VirtoCommerce/vc-platform/tree/master/VirtoCommerce.Platform.Web/Swagger

**Comment by kostyrin** [comment]
in progress
