### ISSUE TITLE
Find out solution to simplify public url configuration for blob storage provider

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#317]
The problem:
Currently, we have to specify a public URL in appsetting.json, which is used to generate a public URL for all static assets that will be processed by the  static ASP.NET files middleware.

![image.png](https://images.zenhubusercontent.com/565ffe4f638e718c995f110d/ee095d05-cfbd-4f7f-a03c-406db8827cd2)

It is very not convenient for initial configuration  on different environments. Need to find solution how to use relative urls instead of absolute urls where it is possible or   find another way to know application url

**Comment by anivirtoway** [comment]
According to asp.net core options, we can override appsettings.json via environmet variable. So we can owerride public urls via environmet variable. We can'not get public domain url via code.

**Comment by tatarincev** [comment]
We decided leave all as is
