### ISSUE TITLE
The settings fields don't display in the setting details blade 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#48]
![image.png](https://images.zenhubusercontent.com/565ffe4f638e718c995f110d/9a6da026-d654-40c2-93b0-45333d1459ce)

**Comment by n2pro** [comment]
fixed by unknown commit
![image](https://user-images.githubusercontent.com/13115017/40969394-1224d656-68b8-11e8-89ed-6af72efe1b29.png)
