### ISSUE TITLE
Platform > "Export New" screen > Page not reopen

### ISSUE THREAD

**Issue by elakhamitova** [VirtoCommerce/vc-platform-core#487]
**Steps:** Logged user in the admin page > Select the "Export New" module > "Export settings" screen is opened > User click to the Close button > Screen is closed > User select the "Export New" again

**Actual result:** Screen not open. The button is unclickable.

**Comment by yecli** [comment]
Please post bugs on Export in Jira. 
In github platform-core repository we should post common platform bugs, not specific for export functionality, e.g. header image issue in Safari.

Please close this one after creating Jira ticket.
