### ISSUE TITLE
Platform > Catalog > Categories & Items > Incorrect view of downloaded images

### ISSUE THREAD

**Issue by elakhamitova** [VirtoCommerce/vc-platform-core#488]
**Steps:** The user is on admin page > Add the image to the item > Save

**Actual result:** Incorrect view of downloaded images
![2](https://user-images.githubusercontent.com/15369310/62382336-ca7d1f00-b566-11e9-8dce-8b38827de3d7.jpg)
![1](https://user-images.githubusercontent.com/15369310/62382339-cbae4c00-b566-11e9-80e7-d5a85704b554.jpg)

**Comment by yecli** [comment]
This bug is related to export Demo env, please post this one and similar in Jira.
Close this one after that.
