### ISSUE TITLE
"Create Order" in subscriptions does not create a new order

### ISSUE THREAD

**Issue by esbef** [VirtoCommerce/vc-platform-core#490]
In demoshop: http://demo.virtocommerce.com/

Subscriptions --> Select an active subscription --> click "Create Order" 

No new order for the subscription is generated. Second click on "Create order" leads to Error 500 (see screenshot)

![Screenshot_2019-08-03 Virto Commerce](https://user-images.githubusercontent.com/29375168/62409955-3bf8b400-b5df-11e9-8959-4f0273132006.png)

**Comment by tatarincev** [comment]
Issue moved to [VirtoCommerce/vc-module-subscription #23](https://github.com/VirtoCommerce/vc-module-subscription/issues/23) via [**ZenHub**](https://www.zenhub.com/)
