### ISSUE TITLE
404 when click on price widget

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-platform-core#501]
I can assume that prices were filled for the Dental catalog through the widget of the product. In the process of price filling, BoltsUSD price list was mistakenly chosen. There were no attachments of the Dental catalog to any price list at that time. Elvira Khamitova filled the prices.
![image](https://user-images.githubusercontent.com/13153256/62765432-c8501e80-ba98-11e9-96bd-5367251ffa3e.png)

https://demovc-admin-v3.azurewebsites.net
Platform version 3.0.0

**Comment by trueboroda** [comment]
Also, BoltsUSD price list has strange items without name. 
![image](https://user-images.githubusercontent.com/13153256/62765804-94c1c400-ba99-11e9-99f9-e2eeb08ca657.png)

**Comment by kostyrin** [comment]
the first problem is fixed already
![image](https://user-images.githubusercontent.com/8361000/63861961-268f6380-c9ac-11e9-900b-c3fa8fd6403c.png)

**Comment by kostyrin** [comment]
the second problem is has missed product in the sample data, look at the screenshot
![image](https://user-images.githubusercontent.com/8361000/63863738-feedca80-c9ae-11e9-8944-10c8cbde21d8.png)
need to fix sample data for v.3
