### ISSUE TITLE
Inventory management of product doesn't work

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-platform-core#503]
After pressing the save button, the values are reset to zero.
![image](https://user-images.githubusercontent.com/13153256/62858919-63006580-bd04-11e9-8807-92f5290fbf0f.png)

**Comment by anivirtoway** [comment]
@trueboroda Cant reproduce, tested in latest dev version. Can you write steps to reproduce?

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/63971187-37bc9b00-caa6-11e9-839a-1e91867d8038.png)
can't reproduce, closed
