### ISSUE TITLE
no shipping and payment methods

### ISSUE THREAD

**Issue by anivirtoway** [VirtoCommerce/vc-platform-core#509]
![image](https://user-images.githubusercontent.com/45942974/62942235-8c8ebf00-bde0-11e9-92a0-aa73003697f6.png)
![image](https://user-images.githubusercontent.com/45942974/62942327-b6e07c80-bde0-11e9-8784-303c9ca23f5e.png)

also for payment
![image](https://user-images.githubusercontent.com/45942974/62942424-e8594800-bde0-11e9-8f08-506f6b3751f3.png)

**Comment by kostyrin** [comment]
look at https://github.com/rdvojmoc/DinkToPdf#install
