### ISSUE TITLE
Migrate to ASP.NET 2.1

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#52]
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1

**Comment by ghd258** [comment]
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1&from=groupmessage
![40894108-c5b9565e-67d9-11e8-9ffe-9b6706109f56](https://user-images.githubusercontent.com/4811375/41009041-2d483bea-6961-11e8-9414-2c7fe0c767ea.jpg)
![40894110-ca3ed0aa-67d9-11e8-8d42-8f0c1b7f82d1](https://user-images.githubusercontent.com/4811375/41009044-30f2b158-6961-11e8-8101-b5008c5f0191.jpg)
namespace WebApp1
{
public class Startup
{
public Startup(IConfiguration configuration)
{
Configuration = configuration;
}

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
        services.Configure<CookiePolicyOptions>(options =>
        {
            // This lambda determines whether user consent for non-essential cookies is needed for a given request.
            options.CheckConsentNeeded = context => true;
            options.MinimumSameSitePolicy = SameSiteMode.None;
        });


        services.AddMvc()
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler("/Error");
            app.UseHsts();
        }

        app.UseHttpsRedirection();
        app.UseStaticFiles();
        app.UseCookiePolicy();

        app.UseMvc();
    }
}

**Comment by tatarincev** [comment]
@ghd258  Thanks, already done
