### ISSUE TITLE
Unable to execute pre-compiled binaries

### ISSUE THREAD

**Issue by eseEroe** [VirtoCommerce/vc-platform-core#522]
I am unable to execute the pre-compiled binaries on my local and test environment. I typically get the errors in the attached screenshot anytime I run "dotnet.exe C:\vc-platform-3\VirtoCommerce.Platform.Web.dll". Please note that I followed the instructions specified at [https://github.com/VirtoCommerce/vc-platform-core#precompiled-binary-getting-started](https://github.com/VirtoCommerce/vc-platform-core#precompiled-binary-getting-started)

In addition, I downloaded the source code and compiled as instructed at [https://github.com/VirtoCommerce/vc-platform-core#source-code--getting-started](https://github.com/VirtoCommerce/vc-platform-core#source-code--getting-started). I still encountered the errors in the attached screenshot.

Please advise on how to fix this issue. Thanks.

![virto-commerce-issue](https://user-images.githubusercontent.com/42136784/63168381-e1724580-c02b-11e9-8dac-317ef5f3ced3.PNG)

**Comment by yecli** [comment]
Hi @eseEroe.
You need to run dotnet VirtoCommerce.Platform.Web.dll from its folder - c:\vc-platform-3\.
So seems the problem is in current folder.

**Comment by ese-erigha** [comment]
Hi @yecli ,
Thanks for the update. The installation works as intended. This issue can be closed.
