### ISSUE TITLE
Cannot generate Simple API key for user account

### ISSUE THREAD

**Issue by eseEroe** [VirtoCommerce/vc-platform-core#525]
The [documentation](https://virtocommerce.com/docs/vc2devguide/development-scenarios/working-with-platform-api) specifies that an HMAC or Simple key be generated on a user account with **Use api** role to facilitate interaction with the platform's Web API.

I currently cannot generate the simple key for a created user account. I typically experience **Error 404** on the page, and clicking on the **Generate** button does nothing.  Please see attached screenshot.

![virto-commerce1](https://user-images.githubusercontent.com/42136784/63258440-f4775680-c273-11e9-8b13-dd44ebdb87f7.PNG)
![virto-commerce2](https://user-images.githubusercontent.com/42136784/63258442-f4775680-c273-11e9-88ca-252467e852c7.PNG)
![virto-commerce3](https://user-images.githubusercontent.com/42136784/63258444-f50fed00-c273-11e9-8517-4ab28160e315.PNG)

**Comment by tatarincev** [comment]
HMAC and simple key authorization are no longer supported and are excluded from platform version 3.0. It is the bug that the widget still exists.

**Comment by eseEroe** [comment]
@tatarincev , Thanks for the prompt response. My question is:  how do I make secure http requests to the Web API on the platform?.

**Comment by tatarincev** [comment]
Now the platform API is accessible only through OAuth Password grand flow (token based authorization). 
You can  authorize and  call the platform API from the swagger UI that is accessible  by follow url  http://{platform v3 host}/docs/ 
or obtain an auth token by direct API call 
POST http://localhost:10645/connect/token 
```JSON
grant_type=password&username=admin&password=store
```

**Comment by eseEroe** [comment]
@tatarincev , Thanks, this clears things up.
