### ISSUE TITLE
I think the discovery path should be '../Modules'

### ISSUE THREAD

**Issue by maooson** [VirtoCommerce/vc-platform-core#79]
https://github.com/VirtoCommerce/vc-platform-core/blob/e59ae71f10479d4b930981c216de3d17495de0c1/VirtoCommerce.Platform.Web/Startup.cs#L99

The discovery path should be '../Modules', right?

**Comment by tatarincev** [comment]
We have symlink Virtocommerce.Platform.web/Modules pointed to the ../Modules folder, that's why it works for us

**Comment by maooson** [comment]
It's ok now, thank you.
