### ISSUE TITLE
Implement UseDbTriggers for record change log for modified objects 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform-core#80]
- Complete replacement functionality that implemented in https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Data/Infrastructure/Interceptors/ChangeLogInterceptor.cs
- Batch - throttling  async saving, in order not to affect to saving time of the main object

Need to do some investigation and write down all places where that audit change longing is used.

**Comment by kostyrin** [comment]
there are different cases:

- IApplicationBuilder.UseMiddleware (ref. https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/AuditMiddleware.cs)
- use EF Core, override SaveChangesAsync and gets entity changes like 
https://github.com/thepirat000/Audit.NET/blob/6feb753ad41cf6a34e0671237d5ea44a4c29c8e7/src/Audit.EntityFramework/AuditDbContext.cs#L185
https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/DbContextHelper.Core.cs
